version: "3"
services:
    rse:
        build:
            context: .
            dockerfile: ./docker/rse/Dockerfile
        links:
            - cache
            - db
            - mimic
        ports:
            - "8000"
    db:
        image: mongo:2.4
        command: --smallfiles
        ports:
            - "27017:27017"
            - "27018:27018"
            - "27019:27019"
            - "28017:28017"
    cache:
        image: redis:2.8
        ports:
            - "6379:6379"
    mimic:
        build:
            context: .
            dockerfile: ./docker/mimic/Dockerfile
        environment:
            CLOUD_BACKUP_API: twinkie
            CLOUD_BACKUP_API_VERSION: v1
        ports:
            - "8900:8900"
