# Default configuration data. This file doubles as documentation of the
# available config settings.
#
# Values here are overridden by values in /etc/rse/rse.conf.
# *Most* of them can be left as-is, but some must be set per-deployment.
# See the inline comments for details. If adding new options, be sure
# to check proper override behavior; config.py may have bugs.
#
# The default settings are based on a standalone server, with mongo and
# memcache both running locally in a default configuration. This is a
# common testing setup.

test_mode: false  # Disables auth checking and enables /all debug channel
token_prefix: ''

# You are unlikely to need to change these.
event_ttl: 120
token_hashing_threshold: 250

mongodb:
  host: localhost  # Accepts a hostname, mongo URI, or list of either
  replica-set: null
  database: rse

memcached:
  timeout: 5
  servers:
    - localhost  # ports can be added with a colon if desired
